[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.1"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
crossterm = "0.29"
ratatui = "0.30.2"
ropey = "1.6"
toml = "1.1"
unicode-segmentation = "1.11"
unicode-width = "0.2"

typ-core = { path = "crates/typ-core" }
typ-buffer = { path = "crates/typ-buffer" }
typ-registry = { path = "crates/typ-registry" }
typ-panel-editor = { path = "crates/typ-panel-editor" }
typ-panel-tree = { path = "crates/typ-panel-tree" }
typ-app = { path = "crates/typ-app" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
